FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY packages ./packages
ENV PYTHONPATH=/app/packages
COPY services/SERVICE_NAME/app ./services/SERVICE_NAME/app
EXPOSE SERVICE_PORT
CMD ["uvicorn", "services.SERVICE_NAME.app.main:app", "--host", "0.0.0.0", "--port", "SERVICE_PORT"]
